//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.25 at 04:12:27 PM CEST 
//


package nl.testwerk.bookface.soap;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.testwerk.bookface.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllBooksRequest_QNAME = new QName("http://testwerk.nl/bookface/soap", "getAllBooksRequest");
    private final static QName _GetAllBooksResponse_QNAME = new QName("http://testwerk.nl/bookface/soap", "getAllBooksResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.testwerk.bookface.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllBooksRequest }
     * 
     */
    public GetAllBooksRequest createGetAllBooksRequest() {
        return new GetAllBooksRequest();
    }

    /**
     * Create an instance of {@link GetAllBooksResponse }
     * 
     */
    public GetAllBooksResponse createGetAllBooksResponse() {
        return new GetAllBooksResponse();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllBooksRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAllBooksRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://testwerk.nl/bookface/soap", name = "getAllBooksRequest")
    public JAXBElement<GetAllBooksRequest> createGetAllBooksRequest(GetAllBooksRequest value) {
        return new JAXBElement<GetAllBooksRequest>(_GetAllBooksRequest_QNAME, GetAllBooksRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllBooksResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAllBooksResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://testwerk.nl/bookface/soap", name = "getAllBooksResponse")
    public JAXBElement<GetAllBooksResponse> createGetAllBooksResponse(GetAllBooksResponse value) {
        return new JAXBElement<GetAllBooksResponse>(_GetAllBooksResponse_QNAME, GetAllBooksResponse.class, null, value);
    }

}
