//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.25 at 04:12:27 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://testwerk.nl/bookface/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.testwerk.bookface.soap;
